services:
  registry_listener:
    image: ${REGISTRY_HOST}/stack-insight
    build:
      context: ../src
      dockerfile: ../docker/ruby/Dockerfile
      cache_from:
        - type=gha,scope=stack-insight
      cache_to:
        - type=gha,scope=stack-insight,mode=max
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - 7000:7000
    environment:
      DOCKER_HOSTS: unix:///var/run/docker.sock
      OTEL_LOG_LEVEL: debug
      OTEL_TRACES_EXPORTER: console,otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel.next/
