source 'https://rubygems.org'

gem 'async-io'
gem 'falcon'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'async-websocket'
gem 'slim'
# gem 'sass'
gem 'sass-embedded'
# gem 'rack', '~> 2.2.8'
# gem 'rackup', '~> 2.1'
gem 'rack'
gem 'rackup'

gem 'json', '>= 2.18'
gem 'jwt', '~> 3.1'
gem 'jwt-eddsa', '~> 0.9'
gem 'ed25519'
gem 'faraday', '~> 2.14'
gem 'faraday-retry', '~> 2.4'
gem 'faraday-net_http_persistent', '~> 2.3'

gem 'stack-service-base'#
# , path: '/home/user/projects/stack-service-base'

# gem 'opentelemetry-sdk'
# gem 'opentelemetry-exporter-otlp'
# gem 'opentelemetry-instrumentation-all'

group :development do
  gem 'minitest'
  gem 'rubocop'
end
