source 'https://rubygems.org'

gem 'async-io'
gem 'falcon'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'async-websocket'
gem 'slim'
gem 'sass'

# gem 'rack', '~> 2.2.8'
# gem 'rackup', '~> 2.1'
gem 'rack'
gem 'rackup'

gem 'stack-service-base'#
# , path: '/home/user/projects/stack-service-base'

# gem 'opentelemetry-sdk'
# gem 'opentelemetry-exporter-otlp'
# gem 'opentelemetry-instrumentation-all'

group :development do
  gem 'rubocop'
end